default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quality_of_life_api_development

test:
  <<: *default
  database: quality_of_life_api_test

production:
  <<: *default
  database: quality_of_life_api_production
  username: quality_of_life_api
  # password: <%= ENV['YOUR_APP_NAME_HERE_DATABASE_PASSWORD'] %>